// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocolbuffer.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "protocolbuffer.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class BackupMsgDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<BackupMsg> {
} _BackupMsg_default_instance_;

namespace protobuf_protocolbuffer_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BackupMsg, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BackupMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BackupMsg, type__),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BackupMsg, origin__),
  1,
  0,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 6, sizeof(BackupMsg)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_BackupMsg_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "protocolbuffer.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _BackupMsg_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _BackupMsg_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\024protocolbuffer.proto\"+\n\tBackupMsg\022\r\n\005t"
      "ype_\030\001 \002(\005\022\017\n\007origin_\030\002 \001(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 67);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protocolbuffer.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_protocolbuffer_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BackupMsg::kTypeFieldNumber;
const int BackupMsg::kOriginFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BackupMsg::BackupMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_protocolbuffer_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:BackupMsg)
}
BackupMsg::BackupMsg(const BackupMsg& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  origin__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_origin_()) {
    origin__.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.origin__);
  }
  type__ = from.type__;
  // @@protoc_insertion_point(copy_constructor:BackupMsg)
}

void BackupMsg::SharedCtor() {
  _cached_size_ = 0;
  origin__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type__ = 0;
}

BackupMsg::~BackupMsg() {
  // @@protoc_insertion_point(destructor:BackupMsg)
  SharedDtor();
}

void BackupMsg::SharedDtor() {
  origin__.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void BackupMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BackupMsg::descriptor() {
  protobuf_protocolbuffer_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_protocolbuffer_2eproto::file_level_metadata[0].descriptor;
}

const BackupMsg& BackupMsg::default_instance() {
  protobuf_protocolbuffer_2eproto::InitDefaults();
  return *internal_default_instance();
}

BackupMsg* BackupMsg::New(::google::protobuf::Arena* arena) const {
  BackupMsg* n = new BackupMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void BackupMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:BackupMsg)
  if (has_origin_()) {
    GOOGLE_DCHECK(!origin__.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*origin__.UnsafeRawStringPointer())->clear();
  }
  type__ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool BackupMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:BackupMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 type_ = 1;
      case 1: {
        if (tag == 8u) {
          set_has_type_();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type__)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string origin_ = 2;
      case 2: {
        if (tag == 18u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_origin_()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->origin_().data(), this->origin_().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "BackupMsg.origin_");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:BackupMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:BackupMsg)
  return false;
#undef DO_
}

void BackupMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:BackupMsg)
  // required int32 type_ = 1;
  if (has_type_()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->type_(), output);
  }

  // optional string origin_ = 2;
  if (has_origin_()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->origin_().data(), this->origin_().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "BackupMsg.origin_");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->origin_(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:BackupMsg)
}

::google::protobuf::uint8* BackupMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:BackupMsg)
  // required int32 type_ = 1;
  if (has_type_()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->type_(), target);
  }

  // optional string origin_ = 2;
  if (has_origin_()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->origin_().data(), this->origin_().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "BackupMsg.origin_");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->origin_(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BackupMsg)
  return target;
}

size_t BackupMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BackupMsg)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // required int32 type_ = 1;
  if (has_type_()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->type_());
  }
  // optional string origin_ = 2;
  if (has_origin_()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->origin_());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BackupMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:BackupMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const BackupMsg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BackupMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:BackupMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:BackupMsg)
    MergeFrom(*source);
  }
}

void BackupMsg::MergeFrom(const BackupMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:BackupMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._has_bits_[0 / 32] & 3u) {
    if (from.has_origin_()) {
      set_has_origin_();
      origin__.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.origin__);
    }
    if (from.has_type_()) {
      set_type_(from.type_());
    }
  }
}

void BackupMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:BackupMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BackupMsg::CopyFrom(const BackupMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BackupMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BackupMsg::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000002) != 0x00000002) return false;
  return true;
}

void BackupMsg::Swap(BackupMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BackupMsg::InternalSwap(BackupMsg* other) {
  origin__.Swap(&other->origin__);
  std::swap(type__, other->type__);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata BackupMsg::GetMetadata() const {
  protobuf_protocolbuffer_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_protocolbuffer_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// BackupMsg

// required int32 type_ = 1;
bool BackupMsg::has_type_() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void BackupMsg::set_has_type_() {
  _has_bits_[0] |= 0x00000002u;
}
void BackupMsg::clear_has_type_() {
  _has_bits_[0] &= ~0x00000002u;
}
void BackupMsg::clear_type_() {
  type__ = 0;
  clear_has_type_();
}
::google::protobuf::int32 BackupMsg::type_() const {
  // @@protoc_insertion_point(field_get:BackupMsg.type_)
  return type__;
}
void BackupMsg::set_type_(::google::protobuf::int32 value) {
  set_has_type_();
  type__ = value;
  // @@protoc_insertion_point(field_set:BackupMsg.type_)
}

// optional string origin_ = 2;
bool BackupMsg::has_origin_() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void BackupMsg::set_has_origin_() {
  _has_bits_[0] |= 0x00000001u;
}
void BackupMsg::clear_has_origin_() {
  _has_bits_[0] &= ~0x00000001u;
}
void BackupMsg::clear_origin_() {
  origin__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_origin_();
}
const ::std::string& BackupMsg::origin_() const {
  // @@protoc_insertion_point(field_get:BackupMsg.origin_)
  return origin__.GetNoArena();
}
void BackupMsg::set_origin_(const ::std::string& value) {
  set_has_origin_();
  origin__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:BackupMsg.origin_)
}
#if LANG_CXX11
void BackupMsg::set_origin_(::std::string&& value) {
  set_has_origin_();
  origin__.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:BackupMsg.origin_)
}
#endif
void BackupMsg::set_origin_(const char* value) {
  set_has_origin_();
  origin__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:BackupMsg.origin_)
}
void BackupMsg::set_origin_(const char* value, size_t size) {
  set_has_origin_();
  origin__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:BackupMsg.origin_)
}
::std::string* BackupMsg::mutable_origin_() {
  set_has_origin_();
  // @@protoc_insertion_point(field_mutable:BackupMsg.origin_)
  return origin__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* BackupMsg::release_origin_() {
  // @@protoc_insertion_point(field_release:BackupMsg.origin_)
  clear_has_origin_();
  return origin__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void BackupMsg::set_allocated_origin_(::std::string* origin_) {
  if (origin_ != NULL) {
    set_has_origin_();
  } else {
    clear_has_origin_();
  }
  origin__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), origin_);
  // @@protoc_insertion_point(field_set_allocated:BackupMsg.origin_)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
